### ISSUE TITLE
pls upgrade to use yargs@^12.0.0 to avoid security vulnerability

### ISSUE THREAD

**Issue by shiup** [Mermade/oas-kit#110]
### Checklist

✗ Medium severity vulnerability found in mem
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/npm:mem:20180117

The latest yargs contains the fix for mem

### Detailed Description
swagger2openapi@2.11.7 > yargs@9.0.1 > os-locale@2.1.0 > mem@1.1.0
(even the latest is only using ` "yargs": "^11.0.0"`)

**Comment by MikeRalphson** [comment]
We're already using yargs ^12.0.2 in the 3.x series. Please upgrade if you can.

**Comment by MikeRalphson** [comment]
Are you pinning to `^2.0.0` or similar? You should just be able to `npm swagger2openapi@latest`

**Comment by codechennerator** [comment]
I don't think so... this happens when I make a clean folder and use ```npm i swagger2openapi@latest```

**Comment by MikeRalphson** [comment]
And you're connecting directly to the main npm repository, no local server, cache or proxy?

The latest at https://www.npmjs.com/package/swagger2openapi is v3.2.13

**Comment by codechennerator** [comment]
Yea, this is all using the main npm repository. It seems my package.json is also on the correct version...
```
{
  "_from": "swagger2openapi@latest",
  "_id": "swagger2openapi@3.2.13",
  "_inBundle": false,
  "_integrity": "sha512-pjF5G4QQPPTM+32A3MXCpbYwi555yPVCbRS4Mz+lL0kUpTHPizeyETvAYQ5RAe+GzWgpoqWLNLiHWIOvGsdlaQ==",
  "_location": "/swagger2openapi",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "swagger2openapi@latest",
    "name": "swagger2openapi",
    "escapedName": "swagger2openapi",
    "rawSpec": "latest",
    "saveSpec": null,
    "fetchSpec": "latest"
  }
```
```
  "dependencies": {
    "call-me-maybe": "^1.0.1",
    "js-yaml": "^3.6.1",
    "node-fetch": "^2.0.0",
    "node-readfiles": "^0.2.0",
    "oas-kit-common": "^1.0.3",
    "oas-resolver": "^1.0.11",
    "oas-schema-walker": "^1.1.0",
    "oas-validator": "^1.1.12",
    "reftools": "^1.0.2",
    "yargs": "^11.0.0"
  },
```

**Comment by MikeRalphson** [comment]
Ok - that part of the mystery solved, the update to yargs 12 was only done after the last publish to npm. I'll cut a new release now.

**Comment by MikeRalphson** [comment]
`v3.2.14` published. Apologies for the confusion.
