### ISSUE TITLE
Body parameter name lost in conversion

### ISSUE THREAD

**Issue by padamstx** [Mermade/oas-kit#113]
When using swagger2openapi (v3.2.13) to convert a swagger 2.0 apispec to openapi 3, it seems that the names of body parameters are lost in the conversion process.  

### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description
There's no "official" way to name the resulting "requestBody" object in the output openapi 3 apispec, but I was hoping that swagger2openapi could add the "x-codegen-request-body-name" extension to the resulting operation.   Since "x-codegen-request-body-name" is a vendor extension, perhaps this request would not apply in the general case.   The "x-codegen-request-body-name" extension (a string property set on an operation within an openapi 3 apispec) is supported by the 
openapi-generator open source project.   I'm not sure if the swagger-codegen project supports this extension or perhaps something similar.
If this request can't be fulfilled, could you please explain how I could augment swagger2openapi to perform this function?   I've heard rumors about a plugin mechanism in swagger2openapi but I'm not sure if it exists yet or how I would use it to perform a function like this.

Thanks for considering this request!

**Comment by padamstx** [comment]
cc: @mkistler

**Comment by MikeRalphson** [comment]
I think we could easily add an `--rbname` option which would set the extension to use to preserve body parameter names. Could you tackle a PR on those lines?

**Comment by padamstx** [comment]
Hi Mike, yes a cmdline option to enable the feature and specify the name of the extension to use makes sense to me.   I'll see if I can whip up a PR for this.

**Comment by MikeRalphson** [comment]
Fantastic, thanks.

**Comment by padamstx** [comment]
This issue was fixed along with #112
