### ISSUE TITLE
skip lint rule

### ISSUE THREAD

**Issue by tstapleton** [Mermade/oas-kit#114]
### Checklist

- [x] Linting issue

### Detailed Description

I'm using oas-linter with oas-validator. `oas-linter` [loads](https://github.com/Mermade/oas-kit/blob/master/packages/oas-linter/index.js#L107) the default rules, and I'd like to disable one. I see:

https://github.com/Mermade/oas-kit/blob/ac18742702367bade1d070ebd4e404d484910bb7/packages/oas-linter/index.js#L32-L34

I copied the lint rules to my project. I can set `rule.skip` to `true` and call `linter.loadRules()` with my updated rules. Setting a breakpoint on the line in the snippet above shows I `rule.skip` evaluates to `true`, but `options[rule.skip]` becomes `options[true]`, which doesn't seem correct. 

Speccy [docs](https://github.com/wework/speccy#config-file) show that `skip` is an array of rule names, e.g. `info-contact`. so maybe those lines should be changed to:

```
if (rule.skip) {
  continue;
}
if (Array.isArray(options.skip) && options.skip.includes(rule.name)) {
  continue;
}
```

That also removes the `&&` from the condition, so a rule could be skipped by defining it in the rules yaml or in the options passed to the validator.

I can give you a PR with this change if it seems correct. Or, maybe I'm doing something wrong?

#### Other stuff

There is an [issue](https://github.com/wework/speccy/issues/163) in Speccy about problems with skipping rules, which could be related.

Thanks!

**Comment by MikeRalphson** [comment]
`rule.skip` is used for a different purpose, i.e. to skip rules when a certain condition is true, such as when processing an `operation` within a `callback` object.

`oas-kit` v4.0.0 will have a new `skipLint` option, and `Speccy` will be updated to use it.

**Comment by tstapleton** [comment]
cool, thanks! i've upgraded and switch to `lintSkip`.

i'd like to have _all_ of the lint rules in my repo, so i can see them in one place. i grabbed the rules from `oas-linter` and `speccy` and made my own `rules.yaml` file. when i call `linter.loadRules('my-rules.yaml')`, it [combines my rules with the rules defined in the repo](https://github.com/Mermade/oas-kit/blob/master/packages/oas-linter/index.js#L239). i can turn them off using `lintSkip` just fine, but i [can't disable them](https://github.com/Mermade/oas-kit/blob/master/packages/oas-linter/index.js#L29) in `my-rules.yaml` (to try to keep the rules defined in one place).

so, can i give you a PR that clears out existing rules so only mine are used? i was thinking something like:
```js
function setRules(s) {
    rules = [];
    return loadRules(s);
}
```

or some other way?

**Comment by MikeRalphson** [comment]
Yep  fire off a PR. Maybe a new `preserve` flag on the `loadRules` function?

**Comment by MikeRalphson** [comment]
Or maybe if we moved this line down a bit? https://github.com/Mermade/oas-kit/blob/7ecb04c6f68dd79e7d715cd448508a009033ae2e/packages/oas-linter/index.js#L29
