### ISSUE TITLE
Docker image(s) available for openAPI Tools like swagger2openAPi ?

### ISSUE THREAD

**Issue by toschder** [Mermade/oas-kit#116]
It would be nice to have Docker images available, containing the Toolkit, especially swagger2openApi Converter.

### Detailed Description
For CI/CD integration it would be helpful to have the tools also available as Docker images, like speccy.io does for the validation. Is there already any docker image available, especially for swagger2openApi ?
If not, it would be helpful to have one.

#### Other stuff

I´m currently only interested in swagger2openApi converter, but I guess there are some others tools to be "Dockerized".

**Comment by MikeRalphson** [comment]
Are you able to help out with a PR or two? It's a great idea.

**Comment by toschder** [comment]
Yes, I´ll start internally anyway and if I got a 1st version completed, I can add a PR here. So, there´s currently noone else already working on that?

**Comment by MikeRalphson** [comment]
That's correct. Thanks for helping out!

**Comment by MikeRalphson** [comment]
`openapi-gui` has a user-contributed `Dockerfile` which might be some kind of starting point. https://github.com/Mermade/openapi-gui/blob/master/Dockerfile

**Comment by MikeRalphson** [comment]
`Dockerfile` added and pushed to Docker Hub as `mermade/swagger2openapi`

**Comment by toschder** [comment]
Thx for the initial version! Would you mind to change the last lines of the Dockerfile to
`...
ENTRYPOINT ["swagger2openapi"]
CMD ["-h"]`
Than it can be called like wework/speccy:
`docker run mermade/swagger2openapi --help` without repeating the "swagger2openapi" command.

**Comment by MikeRalphson** [comment]
Great idea, thanks!

**Comment by MikeRalphson** [comment]
Updated and pushed.
