### ISSUE TITLE
Referenced form param with type="file" converted incorrectly

### ISSUE THREAD

**Issue by padamstx** [Mermade/oas-kit#117]
If an openapi 2 apispec contains a named form parameter with type="file", the resulting schema property ends up as type "string" with no format defined.   It should be converted to a schema property with type="string"/format="binary".

I discovered this while fixing issues #112 and #113.   

### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [x] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ ] Linting issue
- [ ] Resolver issue

### Detailed Description
This issue is caused by the "delete param.type" statement near the end of the processParameter() function.   I think what happens is that when we're processing a form param within an operation, we resolve the reference to find the named parameter, but it has already been processed and the "type" field was deleted, so the "if type='file'" check doesn't get triggered.   

#### Other stuff

Running swagger2open latest version in master

**Comment by padamstx** [comment]
Here's a swagger 2.0 apispec that exhibits the problem: [rbtest.zip](https://github.com/Mermade/oas-kit/files/2658286/rbtest.zip)

**Comment by MikeRalphson** [comment]
Thanks for the analysis.

**Comment by padamstx** [comment]
@MikeRalphson I've added a testcase for this issue under PR #119 .   I've played around a bit with the code to try to solve this, but can't seem to find the correct magic.    Could you please take a look?

**Comment by padamstx** [comment]
In the testcase I added, the expected output currently has the "formTest1" requestBody with schema property "ref_form_param" with type=string, but should also have format=binary since the input apispec specified type=file for the named form parameter.    I left it with only type=string so that the test would pass, but when issue 117 is fixed, the expected output would need to be modified to contain the "correct" output.

**Comment by MikeRalphson** [comment]
Oh ok, good analysis. Thanks.

**Comment by MikeRalphson** [comment]
Could you check the above fix, and that I've amended the tests correctly?

**Comment by padamstx** [comment]
Mike, finally getting to this after Christmas vacation...   I tried this out and it seems to work just fine.   Can we get this in a release?   Thanks for fixing this one!

**Comment by MikeRalphson** [comment]
Will try and cut 4.0.1 tomorrow. There's a regression in the promise/callback logic somewhere.

**Comment by padamstx** [comment]
Node-related question for you...   Currently, I have the 4.0.0 release installed locally in /usr/bin/swagger2openapi (result of running "npm install -g swagger2openapi").   My local git repo has your commit in it for this issue, and I was going to try to temporarily install that in /usr/bin until the real release is ready.   Is there a flavor of "npm install" that I can use to essentially install the command from my local git repo instead of using the registry to locate the official repo?

**Comment by MikeRalphson** [comment]
Glad you got it figured out, I just run everything from my checked out repos. I very, very rarely install my own stuff globally (but do as dependencies).

**Comment by MikeRalphson** [comment]
`v4.01` has just been published. Thanks for all your help on this and the other issues.
