### ISSUE TITLE
Feature Request : Swagger2Openapi provide convertObj as a separate package 

### ISSUE THREAD

**Issue by mrin9** [Mermade/oas-kit#122]
### Feature Request: 
**```convertObj()``` as a separate package** 

I am trying to create a HTML5 ```CustomElement``` which can be used in the browser to display REST documentation and also can be seamlessly integrated with other HTML documents.
I depend heavily on Swagger2Openapi for this.
But, the custom-element that I am building ends up becoming a large element. Upon inspection I found Swagger2Openapi depends upon certain packages that is not needed in modern-browser or modern-node environment. Such as ```esprima``` which is used by ```js-yaml```. 

Would you consider extracting out ```convertObj()``` method and provide it as a separate leaner package for modern node and browser environments?

> Thanks for this amazing set of packages

**Comment by mrin9** [comment]
I wasnt indicating doing it at the cost of losing some functionality or maintaining multiple copies of code.
I was thinking more on the lines where you create a small core like ```convertObj``` with minimal dependency whose job would just be to convert a Swagger JSON to OpenAPI JSON. And then use this as a dependency along with other dependencies like ```js-yaml``` in the existing ```swagger2openapi``` package. 

This however demands some refactoring.

**Comment by MikeRalphson** [comment]
We would need to overcome the loss of resolving functionality as above.

If you're willing to work on this refactoring, I'll happily work on the PR with you.

**Comment by mrin9** [comment]
I just took a cursory look at the code when I requested for this feature 
I will take dig at it after couple of weeks. 
For now I am held up at making the custom-element work. But making it leaner is definitely a goal.

Feel free to close this issue for now if you wish

**Comment by MikeRalphson** [comment]
Happy to leave open, and thanks for the suggestion.

**Comment by MikeRalphson** [comment]
I'm looking into moving to an alternative YAML module, which might bring the bundled size down a bit.

**Comment by mrin9** [comment]
that will be great too !!!

**Comment by MikeRalphson** [comment]
Will post size reduction here when I've got the changeover commit done.

**Comment by MikeRalphson** [comment]
The size reduction from using `yaml` instead of `js-yaml` (and omitting `yaml`/`js-yaml` from `oas-kit-common` entirely) is from 1.2MB to 856KB, around 27%. Maybe not great yet, but it is an improvement. I'll take a look at a `node_modules` map and see if I can find any large modules which can be omitted or replaced for the browser build.

One option that's just ocurred to me is that if you **definitely** know you won't need YAML support at all (i.e. your definitions are already fully resolved or don't contain any external `$ref`s) then we could stub out the `yaml` module with a shim which uses `JSON.parse()` and `JSON.stringify`...

**Comment by mrin9** [comment]
Great!!!,  reducing about 1/3rd of the size is pretty good reduction with least changes to the code, personally I would be satisfied with this.

**Comment by MikeRalphson** [comment]
Looking at a treemap of the Web pack bundle, it may not be deduplicating `node_modules` correctly, so there may be more substantial savings to come...

**Comment by MikeRalphson** [comment]
We're now down to 568KB for all the modules, or roughly 149KB gzipped. Thanks for prompting me to look into this. This should be released during the coming week.

**Comment by MikeRalphson** [comment]
I've added a new webpack config file `webpack.converter.js` (and also a `webpack.validator.js`) which results in a bundle of 214KB (64KB gzipped) for the converter only. I think this is a pretty good reduction, and thank you again for the suggestion.

I'd really appreciate you reporting back if it works ok in your app once released.

**Comment by MikeRalphson** [comment]
Pinging @RomanGotsiy and @bobby-brennan as both are users of this lib in a browser context.

**Comment by bobby-brennan** [comment]
Thanks Mike. Unfortunately I'm still not able to upgrade due to `tweetnacl@0.14` being browser-unfriendly (it tries to parse `process.versions.node`).

**Comment by MikeRalphson** [comment]
Hmm, if I knew how to webpack shim something far down in the `node_modules` hierarchy I would...

**Comment by bobby-brennan** [comment]
I need to get api-spec-converter off of browserify and onto webpack - I think that might magically fix it. Every time I attempt this though I end up losing a few hours before giving up.

**Comment by MikeRalphson** [comment]
Yep, I now know the feeling! `rollup` is supposed to be zero-configuration I think, but only if you're using `import` not common-js modules.

**Comment by MikeRalphson** [comment]
@bobby-brennan one option is to take the last version you could integrate and try and `git cherry-pick` the commit which changes the usage of `should.js` and release a new version if I can mid way on the `3.x` branch. Maybe with a specific semver pre-release tag?

**Comment by RomanGotsiy** [comment]
@MikeRalphson thanks, numbers look great! I will check it in ReDoc and let you know how it worked!

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-kit-common@1.0.7
 - oas-linter@3.0.0
 - oas-resolver@2.0.0
 - oas-validator@3.0.0
 - reftools@1.0.5
 - swagger2openapi@5.0.0
