### ISSUE TITLE
Validation of SecuritySchemes does not call lint

### ISSUE THREAD

**Issue by pderaaij** [Mermade/oas-kit#125]
Whilst writing customer rules for `speccy` I found that the linter is not called for `SecurityScheme` entries in the components field. This now limits me in writing a rule that forces an oauth2 definition to be present.

I am not sure if this is a deliberate choice? If not, then I would propose to call the linter for each entry in `SecurityScheme`. I have it successfully working locally so I can make a PR pretty easy.

**Comment by MikeRalphson** [comment]
Definitely an oversight. A PR would be very welcome!

**Comment by MikeRalphson** [comment]
PR merged. Thanks again!
