### ISSUE TITLE
New rule action for object keys

### ISSUE THREAD

**Issue by pderaaij** [Mermade/oas-kit#128]
## Detailed description

For my custom rule set that I am creating I would love to have a rule that checks the keys of an object according to a pattern. For example, having a custom rule that ensures the property names are in snake_case. 

This is especially tricky in the `schema` object as fields in the schema object are a schema object on its own. I've played around with several options within the current abilities but came short every time. 

## Possible implementation

I would like to introduce a new rule action that targets the keys of an object, applying a pattern to each and every key. 

In my local environment I have this as a rule definition

>      {
>            "name":"schema-property-name-snake-case",
>            "object": "schema",
>            "enabled": true,
>            "description": "parameter must be in snake_case",
>            "keyPattern": { "property": "properties", "value": "^([a-z_])*$" }
>        }

and introduced the following to the linter

```javascript
             if (rule.keyPattern) {
                const { property, value } = rule.patternForKey;
                const target = (property) ? object[property] : false;

                if (target) {
                    const re = new RegExp(value);
                    const keys = Object.keys(target).forEach(key => {
                        options.context.push((options.context[options.context.length - 1] + '/' + key).split('//').join('/'));
                        ensure(rule, () => {
                            should(re.test(key)).be.exactly(true, rule.description);
                        });
                        options.context.pop();
                    });
                }
            }
```

I am curious if this is something we would like to add or is a bad approach.

** Continuing from: https://github.com/wework/speccy/issues/242

**Comment by MikeRalphson** [comment]
Let me check recent changes to our linter here don't already cover that, I may have added the functionality by porting https://github.com/wework/speccy/pull/239 or https://github.com/wework/speccy/pull/232 ...

**Comment by pderaaij** [comment]
With https://github.com/wework/speccy/pull/239 I couldn't get it working. Haven't tried it with the other

**Comment by MikeRalphson** [comment]
I'll try with your example rule and see what I can come up with.

**Comment by MikeRalphson** [comment]
When you say:

> This is especially tricky in the schema object as fields in the schema object are a schema object on its own. 

Do you mean you want to recurse into every sub-schema of a schema object? You may not realise that `oas-kit`'s validator walks all properties of a `schema` object which are themselves `schema` objects, including arrays like `oneOf` etc and calls the linter on each one.

**Comment by MikeRalphson** [comment]
Yep, I've changed it in the validator.

**Comment by pderaaij** [comment]
That is a perfect solution as well. Will do as test run at the office tomorrow.

**Comment by MikeRalphson** [comment]
Great, let me know if any changes are needed to the linter. Thanks for the help.

**Comment by bottoy** [comment]
Hi @MikeRalphson , can you look as well to the responses object - suffers the same issue? Thx

Speccy rules on the "responses" object are not triggered as the validator only works on the 'response' object. We check that the response code is a number so the pattern rule of @pderaaij  would be perfect for this...

It would be something like (oas-validator/index.js near line 778)   

`if (options.lint) options.linter('responses',op.responses,'responses',options);` 

I think. Although the parameters are somewhat guessed ...

**Comment by pderaaij** [comment]
I got it working by using this rule:

```json
       {
            "name":"schema-property-name-snake-case",
            "object": "schema",
            "enabled": true,
            "description": "parameter must be in snake_case",
            "pattern": { "property": "$key", "omit": "properties/", "value": "^([a-z_])*$" }
        }
```

The omit is necessary as the key propagated is in the format of `properties/<property>`.

**Comment by MikeRalphson** [comment]
@pderaaij excellent. May I add your rule(s) to either a new Wiki page or a `contrib.yaml` rules file?

**Comment by pderaaij** [comment]
I've created #134 to enable rule that actually validates that the response key is an integer. Without this change I wasn't able to get a proper rule to validate this.

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-kit-common@1.0.7
 - oas-linter@3.0.0
 - oas-resolver@2.0.0
 - oas-validator@3.0.0
 - reftools@1.0.5
 - swagger2openapi@5.0.0
