### ISSUE TITLE
Prevent oas-linter from loading own ruleset

### ISSUE THREAD

**Issue by pderaaij** [Mermade/oas-kit#129]
### Checklist

- [x] Linting issue

I am having an attempt at letting `speccy` making use of `oas-linter` in stead of the copied in-app linter. The split in loading and applying rules is awesome, but currently it always has the supplied ruleset of `oas-linter` loaded.

This is due the fact it is explicitly in the file, see: https://github.com/Mermade/oas-kit/blob/master/packages/oas-linter/index.js#L241

I am not sure if `speccy` shouldn't be using the default ruleset, but in general it would be nice to either prevent loading of the ruleset provided by `oas-linter` or just clear the present rules and applying new ones later.

Curious to your thoughts on this @MikeRalphson.

**Comment by MikeRalphson** [comment]
Maybe I should move the rules loading out to the validator...

**Comment by MikeRalphson** [comment]
> Maybe I should move the rules loading out to the validator...

Ok, that won't work as the loading code is needed for ruleset chaining (the `require` property), but having a `loadDefaultRules` function exposed by the linter and called by the validator **if the default linter is being used** looks like it works well.

**Comment by pderaaij** [comment]
Thanks for making the change! Any idea when you would like to release this version 3?

**Comment by MikeRalphson** [comment]
Certainly aiming for this week. Could be as early as this afternoon. What are the issues with the `validate` function you mention in https://github.com/wework/speccy/pull/248 ? Anything I can help with?

**Comment by pderaaij** [comment]
Uncertain yet, have to look into it. Plan for tonight.

**Comment by MikeRalphson** [comment]
OK, will hold off, unless an RC release would be helpful?

**Comment by MikeRalphson** [comment]
> Might be something like: 71b0f4a

Yep, there's possibly more like that lurking in there from the change to use `call-me-maybe`.

**Comment by MikeRalphson** [comment]
Without any final assertion, the validator will declare the result of the validation (as opposed to the document itself) as having failed. The user has requested that the document be linted, and thus the linter returning warnings is treated as a failure.

Is that convincing?

**Comment by pderaaij** [comment]
Yes, that makes sense. I might got on the wrong foot as we are calling it warnings. Doesn't come across critical...

I'll make the change in speccy. Thanks for thinking along!

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-kit-common@1.0.7
 - oas-linter@3.0.0
 - oas-resolver@2.0.0
 - oas-validator@3.0.0
 - reftools@1.0.5
 - swagger2openapi@5.0.0
