### ISSUE TITLE
Question re: presence of $ref with other attributes within a schema

### ISSUE THREAD

**Issue by padamstx** [Mermade/oas-kit#130]
I have a model (Configuration) within a swagger 2.0 apispec which (incorrectly) specifies a $ref AND a description for a particular schema property (enrichments):
Here's an example:
```
"definitions": {
    "Configuration": {
      "type": "object",
      "required": [
        "name"
      ],
      "description": "A custom configuration for the environment.",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the configuration."
        },
        "enrichments": {
          "$ref": "#/definitions/Enrichments",
          "description": "An array of document enrichment settings for the configuration."
        }
      }
    }
}
```
swagger2openapi converts the "enrichments" schema property into this:
```
                      "enrichments": {
                        "allOf": [
                            {
                                "$ref": "#/components/schemas/Enrichments"
                            },
                            {
                                "description": "An array of document enrichment settings for the configuration."
                            }
                        ]
                    }
``` 
Is this really the intended rendering of the original "incorrect" schema property definition?   I think I would have expected it to be generated like this:
```
                      "enrichments": {
                          "$ref": "#/components/schemas/Enrichments"
                      }
```
Note that the current version of swagger-parser seems to simply ignore any other field that might be present when $ref is used within a schema (prior versions would load the additional fields).

**Comment by MikeRalphson** [comment]
Yes, that's the 'recommended' way of combining a `$ref` and other properties in JSON Schema drafts < draft 8 I believe. We could make that behaviour configurable if it's causing problems with particular tooling?

**Comment by padamstx** [comment]
Yeah, I think making this behavior configurable (with the default being the current behavior) would be great, and would save us (IBM Cloud Watson services) a lot of time in fixing up our old apispecs prior to converting them to OpenAPI 3.   As you can probably tell from my prior issues, I'm striving to get our apispec conversion step to be as turn-key as possible :)
Thanks!

**Comment by MikeRalphson** [comment]
So an option with 'drop', 'sibling' and 'allOf' values would work?

**Comment by padamstx** [comment]
yeah, perhaps something like `--dropRefSiblings` to indicate that attributes alongside a $ref should simply be ignored/dropped in the conversion.

**Comment by MikeRalphson** [comment]
Yes, I think that was one of the breaking changes in v4. Feel free to suggest better option value names!

**Comment by padamstx** [comment]
Yeah, I think an option called something like --handleRefSiblings with values `remove`, `preserve` and `allOf` would work fine.

I have one question about the 'allOf' option though.  In my "Configuration" example schema above, should the description field (or any other siblings of $ref) appear directly as fields on the main schema object, with the 'allOf' field containing the $ref as its one and only entry in the list, like this:  ?
```
  "enrichments": {
    "description": "An array of document enrichment settings for the configuration.",
    "allOf": [
      {
        "$ref": "#/components/schemas/Enrichments"
      }
    ]
  }
```
I've seen this pattern in a few places.   If the description field itself is an entry within the 'allOf' list, then it's not really associated with the main schema is it?   Just wanted to make sure I understand what the correct pattern recommended by JSON Schema is.   Thanks!

**Comment by MikeRalphson** [comment]
I personally prefer the two-element `allOf` construct, as I find it's clearer as to what is actually being evaluated, rather than having an **all of** containing just one thing. I think @handrews from JSON Schema leans towards the construct as in your comment above, perhaps there is a reason beyond personal preference for that?

**Comment by padamstx** [comment]
After talking with a colleague about this, I think the two-element `allOf` approach will be fine.   And yes, you're right... the description would also be associated with the main schema.   I'm still learning about composed schemas :)

**Comment by MikeRalphson** [comment]
Cool thanks. And the benefit of having an option which takes one of a set of values is we can extend it later if need be.

**Comment by padamstx** [comment]
@MikeRalphson I see you've already committed a fix... You're fast!  :)   Many thanks for jumping on this one.

**Comment by MikeRalphson** [comment]
Yep, it really was a fix too, as the previous implementation could have added an `allOf` outside of a `schema` object (now if you're using `allOf`, it falls back to `remove` outside of `schema` objects, unless you've specified `preserve`).

**Comment by padamstx** [comment]
I pulled your "v5prep" branch to try out the new option but I'm a bit confused.   Did you forget to update swagger2openapi.js to define the new option?   `--refSiblings` doesn't seem to be recognized as a command-line option :)

**Comment by MikeRalphson** [comment]
Probably! Doh. Will fix in a bit.

**Comment by MikeRalphson** [comment]
Ok the CLI option is there and tested. Thanks for catching that!

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-kit-common@1.0.7
 - oas-linter@3.0.0
 - oas-resolver@2.0.0
 - oas-validator@3.0.0
 - reftools@1.0.5
 - swagger2openapi@5.0.0
