### ISSUE TITLE
Add call to linter for content objects

### ISSUE THREAD

**Issue by pderaaij** [Mermade/oas-kit#135]
So I won't forget when I am at home. I found out that the linter isn't called for content objects. Should be done at line 409 in the validator. Will make that change after PR #134 

```javascript
if (options.lint) options.linter('content',content,ct,options);
```

**Comment by MikeRalphson** [comment]
Great, can you make this change to the `v5prep` branch?

**Comment by pderaaij** [comment]
Yes, was able to do a quick PR before I have to leave.

I've changed #134 to merge into `v5prep`as well

**Comment by MikeRalphson** [comment]
#136 has been merged, thanks again!
