### ISSUE TITLE
External issues holding up release of v5

### ISSUE THREAD

**Issue by MikeRalphson** [Mermade/oas-kit#137]
* [x] "+" character in `$ref` target https://github.com/wework/speccy/issues/249 - seems to work ok in the converter, but not standalone in the resolver. Adding resolver tests.

**Comment by pderaaij** [comment]
@MikeRalphson with this issue done all things look ready to release v5 or do you have other items you'd like to add in the new release?

**Comment by MikeRalphson** [comment]
#141 has just come in, which I can take a look at tomorrow. I'd like to nail down the promise issues too if possible.

**Comment by pderaaij** [comment]
I have some time left tonight, will look into the promise thing

**Comment by MikeRalphson** [comment]
Thank you. Could be another missing `throw`.

**Comment by pderaaij** [comment]
Yeah, I've narrowed it down to the catch in `validate` function in the validator: https://github.com/Mermade/oas-kit/blob/master/packages/oas-validator/index.js#L1393

It has been a long time for me that I worked with promises, but if I read it well the reject only holds the error object and I can't see a way in `call-me-maybe` to add an additional argument. So then the conditional added in `speccy` makes sense. But, hey I am not limited by knowledge and experience here ;-)

**Comment by pderaaij** [comment]
Or... it is the other way around. If the issue is in linting it should throw an error and execute the reject promise instead the resolve one.

**Comment by pderaaij** [comment]
Feels for me that the main issue is that prior the use of `call-me-maybe` the error callback was defined as below:

```javascript
.catch(function (err) {
            resolve(options);
        callback(err,options);
        })
        return false;
        .catch(function (err) {
    });
```

Nowadays the signature for `reject` is only the error without any additional parameters. 

So we could say the consumers (as `speccy) have to adhere to this new behavior and do a null check on the presence of the error object. Other options are welcome.

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-kit-common@1.0.7
 - oas-linter@3.0.0
 - oas-resolver@2.0.0
 - oas-validator@3.0.0
 - reftools@1.0.5
 - swagger2openapi@5.0.0
