### ISSUE TITLE
[s2o] can swagger2openapi re-order the fields in a converted "operation"?

### ISSUE THREAD

**Issue by padamstx** [Mermade/oas-kit#141]
I admit this is a weird question/request :)
Swagger2openapi converts a swagger 2 apispec by modifying the in-memory json structure in place, then writing it to the output file.   One byproduct of this approach is that if a swagger 2 operation contains body or form params, then the "requestBody" field (and potentially the "x-codegen-request-body-name" extension) are added at the end of the operation's fields within the converted JSON structure.

Would it be possible to change swagger2openapi so that the "requestBody" and "x-codegen-request-body-name" fields appear directly after the operation's "parameters" field?   This would make the resulting apispec much more readable.

The reason for this request is that within my team's apispecs (the Watson services available on the IBM Cloud), we typically add an extension to the end of an operation which contains a fairly large JSON object (it contains programming examples for various languages which are used when generating API reference materials), plus the operation also might contain a fairly complex "responses" field that includes several different status codes which might each have a non-trivial schema associated with it.   

When we convert such an apispec to openapi 3 via swagger2openapi the result is that we have the operation's "parameters" field defined near the beginning of the operation, but yet the "requestBody" and "x-codegen-request-body-name" fields are located all the way at the end of the operation, after some potentially large/complex fields ("responses" and our programming examples field).
I was starting to research a potential post-conversion step whereby we use some sort of generic JSON manipulation tool (perhaps something like jq) to re-order the fields within an operation's JSON structure, but thought I'd check to see if perhaps swagger2openapi can do this instead.

Apart from just plain old "pickiness", I think there is some value in having the requestBody field appear closer to the rest of the operation's parameters since ultimately that requestBody represents body and/or form params, and it makes the apispec a bit more readable to have them located in close proximity to each other.

**Comment by MikeRalphson** [comment]
It's a good idea and we do do something similar to try and get the `openapi` property to appear at the top. I'll take a look.

**Comment by padamstx** [comment]
Actually, I think we want/need a `x-codegen-request-body-name` extension only for an operation whose requestBody defines a body parameter.   That extension won't be used by the openapi-generator code in the event that the requestBody defines form param(s).   In that case, the names of the form parameters are derived from the schema property names.

**Comment by padamstx** [comment]
I don't think it will cause problems to have the extension there for an operation with form params because it will just be ignored by the openapi-generator code.    
It might create a bit of confusion for users, however, so perhaps at the point where we know the operation has form params we could just delete it, like you mentioned?   If not, then leaving it there is probably not a show-stopper.
The majority of folks that are involved in maintaining these monstrous apispecs are doc writers and so we try not to confuse them any more than is necessary :-)

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-kit-common@1.0.7
 - oas-linter@3.0.0
 - oas-resolver@2.0.0
 - oas-validator@3.0.0
 - reftools@1.0.5
 - swagger2openapi@5.0.0
