### ISSUE TITLE
[s2o] "array of string" form param converted incorrectly

### ISSUE THREAD

**Issue by padamstx** [Mermade/oas-kit#145]
### Checklist

- [ X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

In this zip file - [visrecv4.zip](https://github.com/Mermade/oas-kit/files/2793924/visrecv4.zip) - there's a swagger 2.0 apispec that didn't quite get converted correctly.     Specifically, the form param named "collection_ids" that belongs to the "analyze" operation is defined as an array of string, but swagger2openapi converted that to a schema property of type string instead of an array of string.

**Comment by MikeRalphson** [comment]
Could you simplify your example and add a new testcase for the converter?

**Comment by padamstx** [comment]
Sure, I'll get to that in a bit.

**Comment by padamstx** [comment]
Another secondary problem is the fact that if I run s2o without the -p option, the conversion fails with only
"name: S2OError" printed and no output file created. Adding the -p option allows the conversion to proceed, so there's some sort of issue with the input swagger.yaml file (I assume), but s2o is not properly displaying an error message to indicate what the problem is.

**Comment by padamstx** [comment]
Thanks Mike!

**Comment by MikeRalphson** [comment]
Sorry for the delay, my trip got extended.

Successfully published:
 - oas-resolver@2.2.0
 - oas-validator@3.2.0
 - swagger2openapi@5.2.0
