### ISSUE TITLE
how to resolve from cli

### ISSUE THREAD

**Issue by bskydive** [Mermade/oas-kit#151]
Please, help me to understand resolving in a command line the openApi3.0 yaml file with definitions. 
Your readme for oas-resolver is outdated/broken.

**Comment by bskydive** [comment]
```

const yaml = require('yaml');
const fs = require('fs');

console.log(JSON.stringify(yaml.defaultOptions));

const resolver = require('oas-resolver');

const source = 'api.yaml';
const outputFile = './api-resolved.yaml';

const openapi = yaml.parse(source, {
	schema: 'core'
});

let options = {resolve: true};

resolver.resolve(openapi, source, options)
	.then(function (options) {
		fs.writeFileSync(outputFile, yaml.stringify(options.openapi),'utf8');
	})
	.catch(function (errors) {
		console.log('error-resolver:', errors)
	});
```
returns file with single string 'api.yaml'

**Comment by MikeRalphson** [comment]
When you say "resolve" do you want to resolve only external `$ref`s or both internal and external ones?

**Comment by MikeRalphson** [comment]
> Your readme for oas-resolver is outdated/broken.

What exactly is outdated or broken? I'm happy to add your example to the Wiki if you think it would benefit others?

**Comment by bskydive** [comment]
I make the final version of reamde example. But maybe the better way exist to run it in command line with parameters without hardcoding paths and options?

**Comment by bskydive** [comment]
Outdated and broken because of yaml.safeLoad and yaml.safeDump

**Comment by bskydive** [comment]
https://github.com/Mermade/oas-kit/blob/master/packages/oas-resolver/README.md

**Comment by MikeRalphson** [comment]
Thanks for the clarification. Have you see the `boast` utility in the `swagger2openapi` package. It is a ready built CLI.

**Comment by MikeRalphson** [comment]
> npm i -D yaml fs oas-resolver

You should **not** install modules with the same name (`fs`) as built-in ones using `npm`. They can be malicious.

> Outdated and broken because of yaml.safeLoad and yaml.safeDump

This is an example of using the `oas-resolver` module, you can use any YAML library you like with it. That said, I have made the example more complete and updated it to match the YAML library we now use internally.

**Comment by bskydive** [comment]
Your example is still not valid. My example can be executed, your - not.
By the way, please, use human-readable variable names. It's not obvious to fill 'str' with the yaml file contents.

**Comment by MikeRalphson** [comment]
> Your example is still not valid. My example can be executed, your - not.

Again, if you told me *what* was wrong, rather than just saying *something* was wrong, you'd save us both some time.

> By the way, please, use human-readable variable names. It's not obvious to fill 'str' with the yaml file contents.

I pretty much prefer my variable names the way I chose them.

Neither the example `README` we were talking about or the `resolve` function take a `str` parameter, so, again, I don't even know where you are talking about.

**Comment by bskydive** [comment]
thanks, resolved
