### ISSUE TITLE
--debug causes swagger2openapi to generate invalid files

### ISSUE THREAD

**Issue by ThomasPr** [Mermade/oas-kit#155]
`swagger2openapi --debug` keeps request bodies in the parameters list.

### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [x] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

Swagger 2.0 allows to define "in: body" for parameters, e.g.

    "parameters": [
      {
        "in": "body",
        "name": "body",
        "description": "User object",
        "required": true,
        "schema": {
          "$ref": "#/definitions/User"
        }
      }
    ],

Reference: https://swagger.io/docs/specification/2-0/describing-request-body/

But in OpenAPI 3, the "body" value is no longer allowed for the "in" attribute. Allowed values are only path, header, query and cookie (Reference: https://swagger.io/docs/specification/describing-parameters/#types)

When using `swagger2openapi --debug` to convert a swagger file containing such "in: body", it will appear in the resulting openapi file. The converted openapi file will therefore not be valid. See the attached files as examples. 
It works correctly if I omit the `--debug` option, the resulting openapi file will contain only a requestBody, but no entry in the parameters list. 

#### Other stuff
    $ swagger2openapi --version
    5.2.3

**Comment by MikeRalphson** [comment]
Debugging mode is for debugging `swagger2openapi` itself, not for debugging your OAS document. Please omit this option.
