### ISSUE TITLE
$refs to local filesystem paths are URL encoded, resulting in no such file or directory error

### ISSUE THREAD

**Issue by HeyRatFans** [Mermade/oas-kit#162]
### Checklist

- [ ] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [x] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ ] Linting issue
- [x] Resolver issue

### Detailed Description

When resolving $refs, if the local filesystem path contains spaces (e.g. /some/path/with spaces/swagger.json) the paths are incorrectly URL encoded, resulting in the following error:

`ENOENT: no such file or directory, open '/some/path/with%20spaces/ref.json'`

It would appear the problem is being caused by URL encoding that is being performed by [URL](https://nodejs.org/api/url.html), which translates the spaces to %20 and ultimately results in the files not being found on the local filesystem. With the white-space removed from the path, the parser works fine and our project is validated correctly.

This issue was discovered when we started using speccy to validate our swagger documentation as part of our CI pipeline where the Jenkins job name contained a space. We have worked around it for the time being by renaming the job, but thought we should bring this to your attention.

#### Other stuff

We are using speccy to validate our OpenAPI 3.0 documentation.

**Comment by MikeRalphson** [comment]
Are you able to reproduce this with `oas-kit` directly? Speccy is behind on the version of these packages.

**Comment by HeyRatFans** [comment]
Apologies for the delay, I'll have a look this afternoon and report back.

**Comment by MikeRalphson** [comment]
No problem, should be covered by tests such as `test/resolver/speccy 141`.

**Comment by HeyRatFans** [comment]
Just to confirm the tests added are failing with latest master branch:

```
86 passing (598ms)
2 failing

1) Resolver tests
     speccy 141
       should match expected output:
   Error: ENOENT: no such file or directory, open 'c:\Users\mbeale\Code\oas-kit\test\resolver\speccy%20141\include.yaml'

2) Converter tests
     speccy 141
       should match expected output:
   Error: ENOENT: no such file or directory, open 'c:\Users\mbeale\Code\oas-kit\test\s2o-test\speccy%20141\include.yaml'
```

**Comment by MikeRalphson** [comment]
OK, looks like a problem specific to windows paths, not spaces generally.

**Comment by MikeRalphson** [comment]
@HeyRatFans I don't suppose you could retest latest `master` on windows?

**Comment by HeyRatFans** [comment]
Looks good to me

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by MikeRalphson** [comment]
Included in:
 - oas-resolver@2.2.4

**Comment by swrdfish** [comment]
I am still facing the issue with version **oas-resolver#2.2.4**

```
speccy resolve -o artifacts\document\specification.yaml ../specs/document/specification.yaml
ENOENT: no such file or directory, open 'c:\Users\bighosh\API%20Governance\specifications\specs\common-items\schemas.yaml'
```

**Comment by umeshp7** [comment]
We are also facing this issue. when trying to use oas-resolver for folder containing spaces it tends to fail with "No such file" error. 
[petstore separate yaml.zip](https://github.com/Mermade/oas-kit/files/4725307/petstore.separate.yaml.zip)
Please try to resolve the above folder and let me know if it is failing for you as well. 

@MikeRalphson
