### ISSUE TITLE
Any plans to enable JSON schema for v7

### ISSUE THREAD

**Issue by bret-peterson** [Mermade/oas-kit#163]
I'd like to use if/then/else in the validator and need ajv v6 for the JSON schema v7 support.

### Checklist

- [ ] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ X] Linting issue
- [ ] Resolver issue

### Detailed Description
Pretty much says it all - need ajv dependency updated.

**Comment by MikeRalphson** [comment]
In short, no.

See [here for more details, including a possible workaround using Speccy](https://github.com/Mermade/oas-kit/pull/44#issuecomment-477260748).

OpenAPI 3.0 mandates the use of JSON Schema Draft 5, so it certainly isn't just a case of updating the `ajv` dependency. When/if the alternative-schemas proposal makes it into OpenAPI 3.1 then things may change, but it's still not clear what interaction `oas-kit` would have with alternative schemas.
