### ISSUE TITLE
null fields in examples are removed after conversion

### ISSUE THREAD

**Issue by alexstojda** [Mermade/oas-kit#164]
### Checklist
- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [x] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description
parameters included as `null` in an example seem to be dropped after conversion. This is not ideal as sometimes, for documentation purposes, we want to illustrate all fields in an example. 

Seems like this is a [known issue](https://github.com/Mermade/oas-kit/blob/8d11cc20a696e3766b7dc8441ca955a0bb5b9367/packages/swagger2openapi/index.js#L1392), but hasn't been addressed...

**Comment by alexstojda** [comment]
Thanks for the quick fixes @MikeRalphson ! When can we expect to see this in a release? :)

**Comment by MikeRalphson** [comment]
Hopefully in the next couple of days.

**Comment by alexstojda** [comment]
Great, thanks!

**Comment by MikeRalphson** [comment]
Included in:
 - swagger2openapi@5.3.0
