### ISSUE TITLE
Options parameters overwrite in parallel cycle

### ISSUE THREAD

**Issue by davidebianchi** [Mermade/oas-kit#167]
*swagger2openapi v5.3.0*

### Checklist

Request to code change to avoid possible errors using `swagger2openapi.convertObj` into a parallel promise, or improve docs to specify the options parameter overwrite

### Detailed Description

Code example **with the problem**
```js
const options = {
  patch: true,
  direct: true
}
const promises = [swagger1, swagger2].map(async swagger => {
  return swagger2openapi.convertObj(swagger, options)
})
const openapis = await Promise.all(promises) // --> openapis = [openapiFromSwagger2, openapiFromSwagger2]
```

**Immediate solution**:
```js
const promises = [swagger1, swagger2].map(async swagger => {
  const options = {
    patch: true,
    direct: true
  }
  return swagger2openapi.convertObj(swagger, options)
})
const openapis = await Promise.all(promises)  // --> openapis = [openapiFromSwagger1, openapiFromSwagger2]
```

**Other possible solution**:

Change the code and copy options parameter instead of modify it (it is a breaking change).

**Comment by MikeRalphson** [comment]
Thanks. I've updated the `README` to hopefully make this clearer. At the moment I don't want to make such a breaking change as to the way this currently works. Hopefully this issue will also be helpful for anyone else using promises in parallel.
