### ISSUE TITLE
[Enhancement] Split out linters to allow different rulesets and results.

### ISSUE THREAD

**Issue by elyobo** [Mermade/oas-kit#177]
### Checklist

- [x] Linting issue

### Detailed Description

The linter currently keeps a [module scoped set of rules](https://github.com/Mermade/oas-kit/blob/master/packages/oas-linter/index.js#L9) which `applyRules` modifies.  This means that it's not possible to apply different sets of rules to different documents.

Having the rules be instance scoped, and creating a default instance to which most of the current exports are mapped, would allow the current behaviour to be maintained while also allowing separate linters to be created with different rulesets if required.

For context, I've written a [Jest test runner that wraps the linter](https://www.npmjs.com/package/jest-runner-oas-linter) and was going to take the same approach as eslint - allowing a configuration file at any directory above the file being linted, which would allow it to define appropriate rules for the api docs under that level.  That's not currently possible, because the linting rules from one directory would be added to the same set as another directory, leading to very inconsistent behaviour.

Whether this is actually _of use_ to anyone is a separate question :D  But it seems a simple change to make.

#### Other stuff

N/A

**Comment by elyobo** [comment]
Just realised another issue with the same root cause; the results are scoped to the module too, so my test runner works well for a single run, but if I run it with `--watch` so that it reruns the tests on file changes then any previously seen errors will never be removed.  Being able to instantiate a new linter for each run would solve that.

If you're OK with the idea I'll open a PR.

**Comment by MikeRalphson** [comment]
Closing (sorry it has taken so long) as I'm not sure I agree with the premise of this issue:

> this means that it's not possible to apply different sets of rules to different documents.

If this is necessary, the `options.linter` can be removed or reset.
