### ISSUE TITLE
Bug: swagger2openapi replaces spaces with underscores

### ISSUE THREAD

**Issue by sergei-maertens** [Mermade/oas-kit#181]
### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [x] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

We are making use of polymorphism, where the discriminator field has values restricted to an enum. The enum values contain spaces:

```json
        "Rol": {
            "required": [
                "betrokkeneType",
            ],
            "type": "object",
            "properties": {
                "betrokkeneType": {
                    "title": "Betrokkene type",
                    "description": "Soort betrokkene",
                    "type": "string",
                    "enum": [
                        "Natuurlijk persoon",
                        "Niet-natuurlijk persoon",
                        "Vestiging",
                        "Organisatorische eenheid",
                        "Medewerker"
                    ]
                },
            },
            "discriminator": "betrokkeneType"
        },
```

And one example schema is:

```json
        "Natuurlijk persoon": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/Rol"
                },
                {
                    "$ref": "#/definitions/betrokkene_identificatie_RolNatuurlijkPersoon"
                }
            ]
        },
```

After conversion to OAS 3, the `enum` contains the spaces, but the schema has been turned into:

```yaml
Natuurlijk_persoon:
      type: object
      allOf:
      - $ref: '#/components/schemas/Rol'
      - $ref: '#/components/schemas/betrokkene_identificatie_RolNatuurlijkPersoon'
```

ReDocly works for some reason, and renders the values with underscores, but that's not what the actual values are.

#### Other stuff

Tested on both swagger2openapi 2.11 and 5.3
```
(zrc) ➜  zrc git:(master) ✗ npm list swagger2openapi
zrc@0.19.1 /home/bbt/code/zaken/zrc
└── swagger2openapi@2.11.16 
```

```
(zrc) ➜  zrc git:(master) ✗ npm list swagger2openapi
zrc@0.19.1 /home/bbt/code/zaken/zrc
└── swagger2openapi@5.3.0 
```

**Comment by MikeRalphson** [comment]
I don't believe this is a bug.

From the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#components-object):

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.

Thus spaces are no-longer allowed in top-level schema names.

OpenAPI 2.0 `discriminator` is a simple pointer to the property which determines the schema to use, it has no concept of a `mapping` as in OpenAPI 3.x to get around this problem.

If you can't amend your API design, you can add an `x-discriminator` specification extension to your OpenAPI 2.0 source which will be used in place of the plain `discriminator` property, containing a `mapping` from your `enum` values to the schema names or `$ref`s.

**Comment by sergei-maertens** [comment]
Thank you for the clarification! We shall update our api design.
