### ISSUE TITLE
Swagger2openapi doesn't correctly detect strings

### ISSUE THREAD

**Issue by nulltoken** [Mermade/oas-kit#193]
My understanding of [YAML spec](https://yaml.org/spec/1.2/spec.html#id2804356) tag resolution is that it describes how to detect an integer: it should match the `-?(0|[1-9][0-9]*)` regex.

When a property is valued with an unquoted number that starts with a zero, it looks like swagger2openapi mistakenly treats it as an integer, rather than as a string.

### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description
using the following OpenAPI 2.0
**random.yaml**
```
swagger: '2.0'

info:
  title: Random title
  description: Random description
  version: "0.0.1"
  contact:
    email: qvidal@random.com

host: www.random.com

schemes:
  - https

paths:
  /random:
    post:
      summary: Random summary.
      parameters:
        - name: body
          description: Random body.
          in: body
          schema:
            $ref: '#/definitions/RandomRequest'
          required: true
      responses:
        204:
          description: No Content.
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Error400'

definitions:
  RandomRequest:
    type: object
    properties:
      string_phone_number:
        description: Some explicit string.
        type: string
        example: "0681924019"
      random_phone_number:
        description: Some implicit string.
        type: string
        example: 0681924019                         # /!\ Here
      other_random_phone_number:
        description: Another explicit string number.
        type: string
        example: "681924019"
    required: [random_phone_number]

  Error400:
    type: object
    properties:
      code:
        type: string
        example: "400"
      label:
        type: string
        example: Bad Request
      description:
        type: string
        example: Property "random_date" is required
```

**Running**
```
yarn swagger2openapi --patch --fatal --yaml --outfile random.openapi.yaml random.yaml
```

Produces the following
**random.openapi.yaml**
```
openapi: 3.0.0
info:
  title: Random title
  description: Random description
  version: 0.0.1
  contact:
    email: qvidal@random.com
paths:
  /random:
    post:
      summary: Random summary.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RandomRequest"
        description: Random body.
        required: true
      responses:
        "204":
          description: No Content.
        "400":
          description: Bad request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Error400"
servers:
  - url: https://www.random.com
components:
  schemas:
    RandomRequest:
      type: object
      properties:
        string_phone_number:
          description: Some explicit string.
          type: string
          example: "0681924019"
        random_phone_number:
          description: Some implicit string.
          type: string
          example: 681924019                          # /!\ Here
        other_random_phone_number:
          description: Another explicit string number.
          type: string
          example: "681924019"
      required:
        - random_phone_number
    Error400:
      type: object
      properties:
        code:
          type: string
          example: "400"
        label:
          type: string
          example: Bad Request
        description:
          type: string
          example: Property "random_date" is required
```

We can see that the property `random_phone_number` has been converted from `0681924019` to `681924019`.

#### Other stuff

Using the [recommended OpenAPI 2.0 validator](http://bigstickcarpet.com/swagger-parser/www/index.html) that is pointed at by the issue template shows that when pasting the yaml file, it's converted to its json representation and `random_phone_number` is properly converted to a string, not an integer.

![image](https://user-images.githubusercontent.com/92363/63380288-765fa080-c396-11e9-98b2-2d06cf3f6b30.png)

**Comment by nulltoken** [comment]
Intially discovered by @Amachua in #169 
Extracted to a separate issue to let the initial one focus on date related issues.

**Comment by MikeRalphson** [comment]
@nulltoken what version of swagger2openapi are you using?

**Comment by nulltoken** [comment]
> @nulltoken what version of swagger2openapi are you using?

5.3.1 

Sorry I should have fed the issue with that piece of information to begin with.

**Comment by nulltoken** [comment]
Seems to originate from the `yaml` dependency.

It's now tracked through https://github.com/eemeli/yaml/issues/118

**Comment by MikeRalphson** [comment]
Thanks, I've subscribed to both issues.

**Comment by MikeRalphson** [comment]
From the reply on the other issue, it appears that when using the `core` spec, you do need to quote such values to have them treated as strings.
