### ISSUE TITLE
Resolver should ideally use simplest path

### ISSUE THREAD

**Issue by bzmw** [Mermade/oas-kit#196]
When resolving `$ref` the outputted references should use the shortest most logical reference.

### Checklist

- [ ] Resolver issue

### Detailed Description

Right now when the resolver resolves `$refs` it results in a lot of long very ugly looking references. 

I've put together an example:
[resolveTest.zip](https://github.com/Mermade/oas-kit/files/3561204/resolveTest.zip)

In the example `Resolve.yaml` the schema for `Dog` has two `$ref` which contain references to parameters. The value of the first `$ref` is `#/components/schemas/Cat/allOf/0`. Which ideally it should be `#/components/parameters/parameter_colour` or the full expanded version of the parameter (as it is in Cat)

**Comment by MikeRalphson** [comment]
I think in reducing your testcase you've managed to confuse things (or me, anyway).

`parameters` aren't `schema` objects and so the `allOf`s won't validate, the `$ref`s should probably point inwards to the `schema` property within the `parameters`?

Given I've had to make those changes (plus adding a `responses` object) for the input to validate, it's now unclear what your expected output would look like.

Also including the whole `Parameters.yaml` under `#/components/parameters` doesn't "re-key" in any way the "best place" to find the parameters when you've already directly `$ref`ed them.

I can see that using a final internal `$ref` when the `$ref` is longer than the `$ref` target may be counter-intuitive, but I wonder how often it really happens (and matters) in real life. I'm wary of adding more code complexity here for this.

**Comment by MikeRalphson** [comment]
If we compbine `SchemaCat.yaml` and `SchemaDog.yaml` into one file as they have identical content:

```yaml
type: object
properties:
  colour:
    $ref: "./Parameters.yaml#/parameter_colour/schema"
  size:
    $ref: "./Parameters.yaml#/parameter_size/schema"
```

the output becomes 

```yaml
openapi: 3.0.0
info:
  title: Resolve Test
  version: 1.0.0
paths:
  /pets:
    get:
      parameters:
        - name: parameter_colour
          description: Colour
          in: query
          required: true
          schema:
            type: string
        - name: parameter_size
          in: query
          description: Size
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  parameters:
    parameter_colour:
      name: parameter_colour
      description: Colour
      in: query
      required: true
      schema:
        type: string
    parameter_size:
      name: parameter_size
      in: query
      description: Size
      required: true
      schema:
        type: string
  schemas:
    Cat:
      type: object
      properties:
        size:
          type: string
        colour:
          type: string
    Dog:
      $ref: '#/components/schemas/Cat'
```

which looks to me both short and logical.

**Comment by bzmw** [comment]
Ah yes I see it now. Sorry still a bit new to playing around with OpenAPI.

Let me close this and re-open it when I can get a proper example together.
