### ISSUE TITLE
components with / in it's name marked as invalid

### ISSUE THREAD

**Issue by spaceone** [Mermade/oas-kit#197]
- [X ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains

My components have `/` in it's names. I always properly escape them when they are referenced. The tool at  https://openapi-converter.herokuapp.com/ says they are invalid:
```
status: false
message: component name invalid
context: "#/components/schemas/users/user"
openapi: 3.0.0
```

**Comment by MikeRalphson** [comment]
It's not just about where you reference schema (and other `components` entry) names. The OpenAPI 3.0 spec expressly permits only names matching the following regex:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#componentsObject

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: `^[a-zA-Z0-9\.\-_]+$.`
