### ISSUE TITLE
Unwanted line break in yaml conversion result

### ISSUE THREAD

**Issue by hrobache** [Mermade/oas-kit#201]
When converting an OA2 yaml file into OA3 yaml file, additional line breaks are inserted within the description of each element.

### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [x] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

OA2 description in YAML format before conversion:
--------------------
      description: |
        This call returns all payment accounts that are relevant the PSU on behalf of whom the AISP is connected.
        Thanks to HYPERMEDIA, each account is returned with the links aiming to ease access to the relevant transactions and balances.
        The result may be subject to pagination (i.e. retrieving a partial result in case of having too many results) through a set of pages by the ASPSP. Thereafter, the AISP may ask for the first, next, previous or last page of results.
----------------

OA3 description in YAML format after conversion:
----------------
      description: >
        This call returns all payment accounts that are relevant the PSU on
        behalf of whom the AISP is connected.

        Thanks to HYPERMEDIA, each account is returned with the links aiming to ease access to the relevant transactions and balances.

        The result may be subject to pagination (i.e. retrieving a partial result in case of having too many results) through a set of pages by the ASPSP. Thereafter, the AISP may ask for the first, next, previous or last page of results.

-----------------

The OA3 description in json format is quite fine:
-----------------
                "description": "This call returns all payment accounts that are relevant the PSU on behalf of whom the AISP is connected.\nThanks to HYPERMEDIA, each account is returned with the links aiming to ease access to the relevant transactions and balances.\nThe result may be subject to pagination (i.e. retrieving a partial result in case of having too many results) through a set of pages by the ASPSP. Thereafter, the AISP may ask for the first, next, previous or last page of results.",

**Comment by MikeRalphson** [comment]
These two representations of a multi-line string are functionally identical (only the block / flow style is different).

Currently the `yaml` module used by `oas-kit` does not allow specifying a preference, so for now, this is a `wont-fix`.
