### ISSUE TITLE
some Markdown styling are removed from description

### ISSUE THREAD

**Issue by hrobache** [Mermade/oas-kit#202]
Especially title markdown tags seem to be seen as comments and then removed from the description text 

### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

Example of OA2 in yaml format before conversion
------------------
      description: |
        ### Description
        This call returns all payment accounts that are relevant the PSU on behalf of whom the AISP is connected.
        Thanks to HYPERMEDIA, each account is returned with the links aiming to ease access to the relevant transactions and balances.
        The result may be subject to pagination (i.e. retrieving a partial result in case of having too many results) through a set of pages by the ASPSP. Thereafter, the AISP may ask for the first, next, previous or last page of results.
--------------

Example of OA3 in yaml format after conversion
--------------
      description: >
        This call returns all payment accounts that are relevant the PSU on
        behalf of whom the AISP is connected.

        Thanks to HYPERMEDIA, each account is returned with the links aiming to ease access to the relevant transactions and balances.

        The result may be subject to pagination (i.e. retrieving a partial result in case of having too many results) through a set of pages by the ASPSP. Thereafter, the AISP may ask for the first, next, previous or last page of results.
--------------

**Comment by MikeRalphson** [comment]
I have updated the `yaml` dependency and added a test for this issue, and it is now passing. New release is imminent.
