### ISSUE TITLE
Resolver removes internal refs

### ISSUE THREAD

**Issue by lasssim** [Mermade/oas-kit#205]
When schemas are split into separate files that use internal refs in `allOf` the internal refs get replaced with `{}`. 

### Checklist
- [x] Resolver issue

### Detailed Description

I have these 3 files:
*test.yaml*
```yaml

openapi: 3.0.0
info:
  version: 1.0.0
  title: test
  contact:
    email: asdf@asdf.com
  description: >
tags:
  - name: test
components:
  schemas:
    Entity:
      $ref: "./Entity.yaml"
    Potatoe:
      $ref: "./Potatoe.yaml"

paths:
  "/test":
    get:
      operationId: test
      description: Get all Atoms
      tags:
        - test
      responses:
        '200':
          description: OK

```
*Entity.yaml*
```yaml
type: object
discriminator: 
  propertyName: type
required: [id, type]
properties:
  id:
    type: string
    format: uuid
  type:
    type: string
```

*Potatoe.yaml*
```yaml
allOf:
  - $ref: "#/components/schemas/Entity"
  - type: object
    properties:
      weight:
        type: integer
```

The output of the resolver is:
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: test
  contact:
    email: asdf@asdf.com
  description: ""
tags:
  - name: test
components:
  schemas:
    Entity:
      type: object
      discriminator:
        propertyName: type
      required:
        - id
        - type
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
    Potatoe:
      allOf:
        - {}
        - type: object
          properties:
            weight:
              type: integer
paths:
  /test:
    get:
      operationId: test
      description: Get all Atoms
      tags:
        - test
      responses:
        "200":
          description: OK
```

What I would expect is, that the internal ref in the file *Potatoe.yaml* in the `allOf` is preserved and not changed.

### Other Stuff

When the referenced object is not extracted to an external file (*Entity.yaml*), everything works as expected.

**Comment by MikeRalphson** [comment]
Refs are resolved in a scope. Your potatoe.yaml file does not contain a `components` property.

Basically you cannot refer to objects in the parent or root scope from a child include.

**Comment by lasssim** [comment]
Thx for you reply.

Hmm, I'm not sure if I fully understand why the internal ref gets changed when I don't tell the resolver to  `resolveInternal`?

Is there any other way to achieve what I'm trying to do? I'd like to have every entity in a separate file and model inheritance of attributes with `allOf`as you could see in my example.

**Comment by MikeRalphson** [comment]
The 'internal' refs that are getting resolved are only internal to the external files you're resolving.

'#/components/schemas/Entity` inside `potatoe.yaml` doesn't resolve to anything because there is no `components` top-level property. As I've said, referenced files cannot see back to the parent or root document.

You cannot 'defer' resolution of `$ref`s in included files to later to force this to happen.

The reason it works like this is because you can include a `#fragment` in a `$ref`, thereby including only a fragment of an included file. **However**, internal `$ref`s inside that fragment can see the rest of the included file in scope until resolution of that file concludes.

> Is there any other way to achieve what I'm trying to do? I'd like to have every entity in a separate file and model inheritance of attributes with allOfas you could see in my example.

Yes, simply replace 

```
allOf:
  - $ref: "#/components/schemas/Entity"
```

with

```
allOf:
  - $ref: "./Entity.yaml"
```
