### ISSUE TITLE
validateSync has a misleading name - needs a callback, or treated as promise

### ISSUE THREAD

**Issue by crizo23** [Mermade/oas-kit#211]
### Detailed Description
validateSync() is an unfortunately named method since it's described as “a synchronous  method which returns a boolean”. In fact, if a callback is not set, it's treated as a Promise, and so the library consumer must act on the promise with the .then/.catch syntax. This isn't a problem when the validation succeeds, but when an error is thrown, it rejects and throws like so:

```
catch (ex) {
        console.log('error: ', ex);
        ex.options = options;
        reject(ex);
        throw ex;
    }
```

Result library consumer ends up with an UnhandledPromiseException

#### Other stuff
Even better, perhaps the validateSync method could be changed to resolve any promises and return a boolean. Or, not use "maybe" from call-me-maybe

Using koa-oas3 library, which uses this one

**Comment by MikeRalphson** [comment]
You're absolutely right, this method should have been removed or renamed at the last breaking change release. Apologies. I'll update the docs and flag this for v6.

**Comment by MikeRalphson** [comment]
Has been renamed to `validateInner` in `oas-validator` `v4.0.0`.
