### ISSUE TITLE
Bump better-ajv-errors version in oas-validator?

### ISSUE THREAD

**Issue by jdillard** [Mermade/oas-kit#212]
### Detailed Description

I'm getting the following error:

```
core-js@<3 is no longer maintained and not recommended for usage due to the number of issues.
```

And it looks like `oas-validator@3.3.2` needs to bump it's [better-ajv-errors](https://github.com/Mermade/oas-kit/blob/8e09faaeafb048cce2fe99b9d31e02abbe5c37f3/packages/oas-validator/package.json#L20) dependency to `0.6.7`?

`better-ajv-errors@0.6.7` has an updated dependency of ["core-js": "^3.2.1"](https://github.com/atlassian/better-ajv-errors/blob/038fd9fc18bb73dcf07334eb13a01be925cd6367/package.json#L41).

#### Other stuff

```
swagger2openapi@5.3.2
  └──oas-validator@3.3.2
      └──better-ajv-errors@0.5.7
          └──core-js@2.6.11
```

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-resolver@2.2.7
 - oas-validator@3.3.3
 - reftools@1.0.10
 - swagger2openapi@5.3.3

Thanks again!

**Comment by jdillard** [comment]
Thank you! 🙇
