### ISSUE TITLE
Bump yargs version to 15.3.1 to avoid possible prototype pollution vulnerability 

### ISSUE THREAD

**Issue by rafaelbdutra** [Mermade/oas-kit#218]
Medium severity vulnerability found in `yargs-parser`, transitive dependency: `oas-resolver` -> `yargs` -> `yargs-parser`

**Vulnerability:** Prototype Pollution
**Source:** https://snyk.io/vuln/npm:yargs-parser

Vulnerability fixed on [yargs-parser v18.1.1](https://github.com/yargs/yargs-parser/releases/tag/v18.1.1) and [yargs v15.3.1](https://github.com/yargs/yargs/releases/tag/v15.3.1)

Could you please bump yargs version to fix this vulnerability?

**Comment by MikeRalphson** [comment]
See #219 which I guess is the same issue.

**Comment by MikeRalphson** [comment]
Fixed in:
 - oas-linter@3.1.1
 - oas-resolver@2.3.2
 - oas-schema-walker@1.1.4
 - oas-validator@4.0.2
 - reftools@1.1.1
 - swagger2openapi@6.0.2
