### ISSUE TITLE
Bump oas-validator ajv dependency to 6.12.3

### ISSUE THREAD

**Issue by lucaslago** [Mermade/oas-kit#261]
Hi, any plans on updating AJV to 6.12.3? That version has a patch for a prototype pollution vulnerability on AJV https://snyk.io/vuln/SNYK-JS-AJV-584908.

I'm happy to try to get a PR going if that's aligned with this package's goals.

**Comment by MikeRalphson** [comment]
Thanks. The current plan is to remove `ajv` in the next major version, and replace with either https://github.com/ExodusMovement/schemasafe or https://github.com/hyperjump-io/json-schema-validator depending on whichever gets us better error messages.

**Comment by MikeRalphson** [comment]
I should have made clear, the change to remove `ajv` is imminent.

**Comment by lucaslago** [comment]
@MikeRalphson that's great news, is there a planned date for that release?

**Comment by MikeRalphson** [comment]
Let me see if there is milestone date on `schemasafe` coming out of RC stage...

**Comment by MikeRalphson** [comment]
`oas-validator@5.0.0` has been released which addresses this security vulnerability.
