### ISSUE TITLE
The ajv^5.5.2  is susceptible to prototype polution

### ISSUE THREAD

**Issue by scheu** [Mermade/oas-kit#274]
The oas-validator and swagger2openapi use ajv@5.5.8, which is susceptible to prototype polution

https://github.com/HoLyVieR/prototype-pollution-nsec18/blob/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf

Please upgrade to ajv@6.12.3 or higher.

**Comment by MikeRalphson** [comment]
Dupe of #261 / #262

**Comment by MikeRalphson** [comment]
`oas-validator@5.0.0` has been released which addresses this security vulnerability.
