### ISSUE TITLE
oas-validator, how to read errors

### ISSUE THREAD

**Issue by Havunen** [Mermade/oas-kit#289]
Hi,

oas-validator readme looks like this:
https://github.com/Mermade/oas-kit/blob/master/packages/oas-validator/README.md

# oas-validator

Usage:

```javascript
const validator = require('oas-validator');
const options = {};
validator.validate(openapi, options, function(err, options){
  // options.valid contains the result of the validation
  // options.context now contains a stack (array) of JSON-Pointer strings
});
```

If the callback argument of `validate` is omitted, a Promise is returned instead.

See here for complete [documentation](/docs/options.md) of the `options` object.

What is the options object refering in the comment? To the constant variable declared before calling validator.validate or to the second parameter? I tested this and it seems second parameter is null when there are errors? 

The actual problem I'm having is how does one read all validation errors after validating the document? I want to do some processing on for each error, maybe simple console.log example would be nice!

**Comment by MikeRalphson** [comment]
I've changed the README example to use the Promises syntax as it's clearer without the unintended shadowing of the `options` variable.

Please note (as added) `oas-validator` is an assertion-based validator, so it will stop on the first error.
