### ISSUE TITLE
why does browser not output json?

### ISSUE THREAD

**Issue by martin0** [Mermade/oas-kit#311]
browser conversion output at https://mermade.org.uk/openapi-converter
outputs indented text, not json

### Checklist

unsure here
- [ ] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ ] Linting issue
- [ ] Resolver issue

### Detailed Description
browser conversion output at https://mermade.org.uk/openapi-converter
outputs indented text, not json
I've tried it with both petstore and my actual swagger input file
https://interactivebrokers.github.io/cpwebapi/swagger.json

#### Other stuff

https://github.com/asyncee/swagger_codegen

**Comment by MikeRalphson** [comment]
You're probably seeing YAML. If you use the API you can specify `application/json` in the `Accept` header.

**Comment by martin0** [comment]
I ran from command line instead and it produced json.
this could be daunting if someone hasn't used node before

**Comment by martin0** [comment]
thanks for your reply Mike

**Comment by MikeRalphson** [comment]
The command line can detect whether you're outputting to a json or a yaml file.

I don't think there's anything daunting about it.

**Comment by martin0** [comment]
setting up node and packages etc

**Comment by MikeRalphson** [comment]
It's a node package, it needs node.js - there is a Docker file if you prefer.

**Comment by martin0** [comment]
my point is the web browser experience should generate json by default.
otherwise its necessary to burrow into some hole that is not the main goal of the user
i'm thinking that simple modification would make a huge issue to user experience :-)
