### ISSUE TITLE
Vulnerability in y18n

### ISSUE THREAD

**Issue by psc-knowis** [Mermade/oas-kit#316]
Hi! I just saw that one of the used dependencies y18n is reported to have a vunerability. The vulnerability is fixed in y18n@5.0.5. Is it possible for you to use that version in order to get rid of that vulnerability? That would be great and very helpful for me.

### Detailed Description
y18n vulnerability - https://snyk.io/test/npm/swagger2openapi

Thanks in advance!

**Comment by MikeRalphson** [comment]
It looks like PR #312 will fix this. I'll update deps, test and cut a new release soon. Thanks.

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-resolver@2.5.3
 - oas-validator@5.0.4
 - reftools@1.1.7
 - swagger2openapi@7.0.4
