### ISSUE TITLE
Update workflows to automate package-lock.json checks & updates

### ISSUE THREAD

**Issue by DjangoFett** [Mermade/oas-kit#333]
Update the existing CI workflows to better manage repetitive actions around the package-lock.json file management 

### Checklist

- [ ] On any push not to master fail if package-lock.json has been modified
- [ ] On push to master, build the package-lock.json file from package.json

### Detailed Description
When I was was updating the contributing file I had noticed there is a requirement to not upload a `package-lock.json`. It's reasonably easy to do so by accident. An update to the CI workflow can check to see if that's included. I don't know how you manage your package-lock.json module but another workflow could be added to potentially manage that as well.

**Comment by MikeRalphson** [comment]
This is possibly complicated by the fact that a) maintainers should be able to push package-lock.json and b) there are multiple package-lock.json files, one per package in the mono-repo.

**Comment by MikeRalphson** [comment]
I've had a thought - that maybe we should address this in a different way - check `package-lock.json` for the things which are potentially problems:

* The `resolved` URL should be `https://`
* The `resolved` URL should point to one of a number of permitted registries - default `[registry.npmjs.org]`
* The entry should have an `integrity` field

Maybe there is already a GitHub action which does this?

**Comment by MikeRalphson** [comment]
See https://github.com/lirantal/lockfile-lint

**Comment by MikeRalphson** [comment]
We now check the `package-lock.json` with https://github.com/Mermade/package-lock-audit
