### ISSUE TITLE
Difference in output between CLI and .convert Obj()

### ISSUE THREAD

**Issue by mrdasher** [Mermade/oas-kit#340]
Hi,

I hope someone can help me out with my issue.
I am trying to convert a Swagger file into OpenApi 3.0.x.

When I do this by command line I am completely satisfied.
I imported the converted file in my editor (https://www.apicur.io/) and the editor informs me about zero issues.
So far so good.

Now I would like to automate some steps and I am using the swagger2openapi-lib from a JavaScript.
When I import the converted file from my JavaScript in my editor it complains about 169 issues.
Issues about unexpected properties like: schemes, consumes, produces, type etc.
When I compare the output of the JavaScript with the output of the command line, I also see differences.

Next step was to look into to documentation of the options-object, maybe I can resolve these issues.
I added a few different boolean options like: patch, direct, externalRefs, resolveInternal.
I did not try any combinations of above options.
I am not able to create a valid OpenApi 3.0.x by a JavaScript. 

My script lookes like this:
	const converter = require('swagger2openapi');
	var fs = require('fs');

	let api = "system-lnng";
	let version = "1.9.4";

	// Convert Swagger/OAS2.0 to OAS3.0
	var swaggerFile = "./" + api + "-" + version + "-oas/api.json";
	var swaggerContent = JSON.parse(fs.readFileSync(swaggerFile, {encoding: 'UTF8'}));

	let options = {};
	options.patch = true;
	options.direct = true;

	converter.convertObj(swaggerContent, options, function(err, options){});
	var oasContent = options.openapi;

	// Edit description of converted Swagger/OAS2.0 aka OAS3.0
	oasContent.info.description = version;

	//Debug
	fs.writeFileSync('convertedSwaggerAkaOAS3.0.json', JSON.stringify(oasContent) , 'utf-8');

Why is the output from .convertObj() so different compared to the output of the command line?
What am I missing? Am I using the right approach?
Is swaggerContent a valid object for the converter?

Any help would be appreciated.

Dennis

Some background information:
I am a (performance) tester/test automation engineer and for testing purposes I am currently looking into mocking of API's with https://microcks.io/. I have to import an OAS3.0 with examples to create mocks in Microcks. I add the examples to the OAS3.0 by an editor https://www.apicur.io/.
Our source system doesn't provide OAS3.0 only Swagger. So therefore we have to convert from Swagger to OpenAPI 3.0.x first.
When a new version of the API appears, I would like to merge the examples of the previous version of the API into the new version, as a base set of examples. So that I only have to update the examples to the new version, if required/necessary.

By searching the Internet I found this repository and this looks very promising.

**Comment by MikeRalphson** [comment]
You need to access the result of the `convertObj` function either by `await`ing the Promise, or in the callback function. In your example code you are accessing the result of the function before it completes. If you are accessing `options.openapi` for the result, you do not want to set `options.direct`.

**Comment by mrdasher** [comment]
Thank you @MikeRalphson  for your very quick response.

I managed to put the script into an `async function main(){}` and added the `await` statement.
I removed the `options.direct` statement.
The result of the JavaScript is now exactly the same as by command line.

Thank you very much for your help.

Dennis
