### ISSUE TITLE
Linter - need more detail in the message

### ISSUE THREAD

**Issue by vk342** [Mermade/oas-kit#418]
when running linter  `npx oas-validate --lint -v -p my-schema.yaml` getting the following error message(s)

schema-properties-type if.then test failed:undefined != object
schema-properties-type if.then test failed:undefined != object
schema-properties-type if.then test failed:undefined != object
...

these messages are impossible to cross reference back to original schema.
should include in an object that triggered the rule

### Checklist

- [ y] Linting issue

### Detailed Description

oas-linter/index.js, line 223

`should(thenProp).equal(rule.if.then.value,rule.name+' if.then test failed:'+thenProp+' != '+rule.if.then.value);`

add object info:

`should(thenProp).equal(rule.if.then.value,rule.name+' if.then test failed:'+thenProp+' != '+rule.if.then.value + '\n' + JSON.stringify(object, undefined, 4));`

**Comment by MikeRalphson** [comment]
Thanks for the error report. Rather than stringifying the object causing the issue, I think it would be better to surface the JSON Pointer to where the object **is**. Is this not included in the current output (I need to check)?

**Comment by MikeRalphson** [comment]
Are you able to share an OpenAPI definition which causes this behaviour?

**Comment by vk342** [comment]
I agree that the pointer would be better than the full object. It is not
currently included.

regarding definition: it is quite long, but an example of failing item
would be:

paths:
  /transaction/{transactionId}:
    parameters:
    - $ref: '#/components/parameters/transactionIdParam'
    put:
      operationId: putTransaction
      description: Update a transaction...
      requestBody:
        content:
          application/json:
            schema:
              #type: object
              properties:
                txnId:
                  type: string
                  description: Unique transactionID.

**Comment by MikeRalphson** [comment]
Thanks - are you using a custom rule or the stock ones? (Sorry should have asked with the previous q.)

**Comment by MikeRalphson** [comment]
Can reproduce, thanks.

**Comment by MikeRalphson** [comment]
Cherry-picked to `main`

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-linter@3.2.2
 - oas-resolver@2.5.5
 - oas-validator@5.0.6
 - swagger2openapi@7.0.6
