### ISSUE TITLE
swagger2openapi报错，Swagger schema parse error!

### ISSUE THREAD

**Issue by amberlwan** [Mermade/oas-kit#594]
### Checklist

- [ ] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ ] Linting issue
- [ ] Resolver issue

#### Other stuff

convertObj方法解析get请求，其中路径参数path和query参数同时拥有的时候会有这个报错

**Comment by MikeRalphson** [comment]
Google translate gives me

> The convertObj method parses the get request, and this error will be reported when the path parameter path and query parameter have both

Please could you include a snippet (or gist) of your input OpenAPI document and copy the error message you get?
