### ISSUE TITLE
Swagger 2.0 to 3.0 convertor for SwashBuckle.core (.Net) 

### ISSUE THREAD

**Issue by sourabhagrawal23** [Mermade/oas-kit#611]
Hi,
Do we have any library which can be used in Swashbuckle implementation of Swagger in .Net code base which generated 2.0 documentation as of now.

Something similar to [swagger2openapi](https://github.com/Mermade/oas-kit/tree/main/packages/swagger2openapi)?

**Comment by MikeRalphson** [comment]
I'm afraid I know nothing about Swashbuckle. Your other issues such as https://github.com/domaindrivendev/Swashbuckle.WebApi/issues/1092 seem to be on repos more likely to get you an answer.

Good luck!
