### ISSUE TITLE
Swagger2openapi command throws 'Microsoft JScript Compilation Error' while running the file

### ISSUE THREAD

**Issue by Hiral-Dadhaniya** [Mermade/oas-kit#73]
Hi,

I have cloned project swagger2openapi, and trying to run the existing file(Before validating my openapi spec) from the repo using given commands.

**For example:** 
Running from command line
> swagger2openapi --version ./test/validate/extrnal-docs-no-servers/openapi.yaml
This throws: Microsoft JScript Compilation Error- Code:800A03F6 (Same for all other files)

As list of all supported versions not mentioned on webpage, would like to know/confirm, does this require any specific version of node, npm or what?
Currently, I am using latest versions:
node: 10.3.0
npm: 6.1.0

Thanks,
Hiral

**Comment by Hiral-Dadhaniya** [comment]
So 'node swagger2openapi' works well and gives the output whole yaml file content. Does that mean yaml is valid? BTW, i am not using chakra-core. So, is there a way to resolve JS error?

**Comment by MikeRalphson** [comment]
`swagger2openapi` is the converter (which writes to stdout if not given a filename with the `-o`/`--output` option). To validate an OAS document, you can use `testRunner` as per the README.

To be able to run `swagger2openapi` without using `node ...` on Windows, I think you'll have to install it globally with `npm i -g swagger2openapi`, this will install the shortcut for you (this won't affect `testRunner` though). 

As to associating `.js` files with node.js - I'm afraid I don't use Windows any more, but something like [this](https://gist.github.com/rsbohn/1924887) might help.

**Comment by Hiral-Dadhaniya** [comment]
Yes, would like to validate OAS document. This will be helpful for now.
Thanks for your prompt response.

**Comment by Hiral-Dadhaniya** [comment]
Looks like changes are going on for swagger2openapi repo. And i think, now it's under oas-kit. So any major changes to this? And oas-linter allows to create new own rules Or better to use speccy instead?

**Comment by MikeRalphson** [comment]
There certainly have been changes, but I don't think it will affect your issues with Windows running the `.js` file with the wrong Javascript interpreter (instead of Node.js).

At the moment, `oas-validator` (the CLI for `oas-linter`) doesn't let you amend or override the `rules.yaml` file (unless you edit it manually, or call the validator from your own application), so for the moment, `speccy` is a more flexible alternative.

**Comment by MikeRalphson** [comment]
Closing this as it is an installation issue, not an issue with oas-kit. See https://stackoverflow.com/questions/36540555/getting-microsoft-jscript-compilation-error
