### ISSUE TITLE
Installation Instructions Unclear

### ISSUE THREAD

**Issue by ansonkao** [Mermade/oas-kit#91]
### Detailed Description
I'd like to do a conversion from 2.0 to 3.0., but I'm having trouble figuring out how to use this repo because there are no installation instructions. 

I'm assuming this is an npm package that I can install via `npm install -g swagger2openapi` and that command runs but then it doesn't become a recognized command on my mac terminal. I can't tell if that's an issue on my machine or if the repo was never intended to function this way.

Can you provide basic beginners installation instructions? ❤️

**Comment by MikeRalphson** [comment]
The mono-repo README to the individual `swagger2openapi` [README](https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/README.md).

It seems we've got away without having explicit installation instructions up to now, as this is a perfectly normal node.js module.

You're right in that there is an npm package of this name as you say as can be seen from browsing npmjs.org.

The [package.json](https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/package.json) defines `swagger2openapi` in the `bin` section, so this should provide an executable command assuming your `npm` is working correctly.

What does `which swagger2openapi` return?

I'll update the README with a simple note about installing with `npm` once we get to the bottom of why it isn't working for you.

**Comment by ansonkao** [comment]
Thanks, for the response, Mike. 

I'm doing this:
```
$ npm install -g swagger2openapi
  ...
  ... Successful installation ...
  ...
+ swagger2openapi@3.2.8
```

And then this is the resulting behaviour:
```
$ swagger2openapi
-bash: swagger2openapi: command not found
```
I'm on npm 6.1.0 via nenv 0.0.6

Is this how most users are using it? Or are you cloning the repository and using it some other way? I tried that too but unclear on the right approach. 

Thanks!!

**Comment by ansonkao** [comment]
Pardon me: 

```
$ which swagger2openapi
```
...returns a blank line

**Comment by ansonkao** [comment]
I just confirmed that I am able to `$ npm install -g [ARBITRARY NEW NPM CLI PACKAGE]` and the new commands work, so my npm setup is generally fine. Perhaps there is something in the swagger2openapi package that needs to be adjusted?

**Comment by MikeRalphson** [comment]
Because I develop swagger2openapi, obviously I have a clone of the git repo and not an installed copy.

I've just tried `npm i -g --verbose swagger2openapi` and I got no errors or warnings.

The relevant section of that output seems to be

```
npm info linkStuff swagger2openapi@3.2.8
npm verb linkBins [ { swagger2openapi: './swagger2openapi.js',
npm verb linkBins     'oas-validate': './oas-validate.js',
npm verb linkBins     'oas-resolve': './oas-resolve.js' },
npm verb linkBins   '/home/mike/.nvm/versions/node/v8.10.0/bin',
npm verb linkBins   true ]
/home/mike/.nvm/versions/node/v8.10.0/bin/swagger2openapi -> /home/mike/.nvm/versions/node/v8.10.0/lib/node_modules/swagger2openapi/swagger2openapi.js
/home/mike/.nvm/versions/node/v8.10.0/bin/oas-validate -> /home/mike/.nvm/versions/node/v8.10.0/lib/node_modules/swagger2openapi/oas-validate.js
/home/mike/.nvm/versions/node/v8.10.0/bin/oas-resolve -> /home/mike/.nvm/versions/node/v8.10.0/lib/node_modules/swagger2openapi/oas-resolve.js
```

Do you have something similar?

`which swagger2openapi` indicates a binary/link has been created (in my case under my `nvm` directory). This was using npm v6.1.0 on Linux. `swagger2openapi --help` works as expected.

I'm afraid I'm unfamiliar with nenv but maybe that's the problem?

**Comment by ansonkao** [comment]
Hi Mike,

I tried it on a different machine and it works. I think the original machine has some sort permissions lock down issues. Thanks for your help - I'll let you know if I find out anything you need to know, but going to assume the problem is on my end and so closing this.

I do still think it would be worth adding the basic installation instructions as discussed, and so added https://github.com/Mermade/oas-kit/pull/93. 

Cheers! 🙌
